version: '3.8'

services:
  postgresdb_ms_portfolio_development:
    image: postgres
    restart: unless-stopped
    container_name: go_postgresdb_ms_portfolio_development
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
      - TZ=Asia/Jakarta
    ports:
      - $DB_PORT:5432
    volumes:
      - postgresdb_ms_portfolio_development_volume:/var/lib/postgres
    networks:
      - portfolio-backend-network

  ms_portfolio_development:
    container_name: go_ms_portfolio_development
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.development
    ports:
      - $GO_PORT:$GO_PORT
    depends_on:
      - postgresdb_ms_portfolio_development
    environment:
      - DB_HOST=go_postgresdb_ms_portfolio_development
      - DB_PORT=5432
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - TZ=Asia/Jakarta
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - REDIS_PASSWORD=$REDIS_PASSWORD
    volumes:
      - /Users/ekoagustina/Documents/Project/BE/go/Portfolio/env_go_ms_portfolio/.env.development:/app/ms_portfolio/.env.development
    stdin_open: true
    tty: true
    networks:
      - portfolio-backend-network

volumes:
  postgresdb_ms_portfolio_development_volume:

networks:
  portfolio-backend-network:
    external: true
